In [32]:
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler

In [33]:
# Cargar dataset
csv_path = Path().resolve().parent / "data" / "WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(csv_path)

In [34]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [35]:
# Eliminar CustumerID ya que no aporta ningun valor
df = df.drop(["customerID"], axis=1)

In [36]:
# Convertir 'TotalCharges' a numérico
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [37]:
# Convertir 'SeniorCitizen' a categórico
df["SeniorCitizen"] = df["SeniorCitizen"].astype(str)

In [38]:
# Aplicar One-Hot Encoding a variables categóricas
df = pd.get_dummies(df, drop_first=True)

In [39]:
# Manejar valores nulos
df.fillna(df.median(), inplace=True)

In [40]:
# Escalar variables numéricas
scaler = StandardScaler()
numeric_cols = ["MonthlyCharges", "TotalCharges", "tenure"]
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [41]:
df.head()

,tenure,MonthlyCharges,TotalCharges,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,-1.277445,-1.160323,-0.994242,False,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0.066327,-0.259629,-0.173244,True,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,-1.236724,-0.362660,-0.959674,True,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0.514251,-0.746535,-0.194766,True,False,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,-1.236724,0.197365,-0.940470,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True

In [44]:
# Definir la ruta para guardar el dataset limpio
cleaned_csv_path = Path().resolve().parent / "data" / "cleaned_telco_churn.csv"
# Guardar dataset limpio
df.to_csv(cleaned_csv_path, index=False)

In [43]:
print("✅ Datos limpios y guardados en 'cleaned_telco_churn.csv'")

✅ Datos limpios y guardados en 'cleaned_telco_churn.csv'